###########################################################
#
# Makefile for all three programs in Project 2.
#
###########################################################
default: proj2a proj2b proj2c

proj2c: proj2c.c
	gcc -lpthread -std=c99 proj2c.c -o proj2c
proj2b: proj2b.c
	gcc -lpthread -std=c99 proj2b.c -o proj2b
proj2a: proj2a.c
	gcc -lpthread -std=c99 proj2a.c -o proj2a 
clean: 
	rm proj2a.o proj2b.o proj2c.o 